### ISSUE TITLE
Saving state too frequently

### ISSUE THREAD

**Issue by knappa** [NutritionalLungImmunity/girder-nlisim#11]
In `tasks.py`, the generator `run_iterator` gets a save of the global state after each new item comes out. See below:
```
            for state, status in run_iterator(simulation_config, target_time):
                current_time = state.time
                logger.info(f'Simulation time {state.time}')
                with TemporaryDirectory() as temp_dir:
                    temp_dir_path = Path(temp_dir)
                    generate_vtk(state, temp_dir_path)

                    step_name = '%03i' % time_step if status != Status.finalize else 'final'
                    girder_config.upload(simulation['_id'], step_name, temp_dir_path)
                    girder_config.set_status(
                        job['_id'], JobStatus.RUNNING, current_time, target_time
                    )

                time_step += 1
```
However I'm fairly certain that one step of this iterator does not correspond to a single time step in the model, or even a consistent movement forward in time. Rather, it corresponds to the evaluation of a single module. This means we are generating too much data and at the wrong time.

This means that resulting 2d graphs don't really have an x-axis that makes much sense. Also, slowness.

**Comment by knappa** [comment]
My latest commit (63c8399a4378a717d65a87059a737c1f7c71bd5d) gives a temporary & minimal fix for this issue.

**Comment by jbeezley** [comment]
Looks fine to me as a mitigation.  This code never was updated after the time step change you made.  As far as a long term solution, I suppose we want to generate a module that performs this logic.  The only hesitation I have is that I would like the simulation to be runable standalone with an identical config.  I suppose we could inject this module dynamically when run inside the celery task context.

This also begs the question of what the output interval should be in general.

**Comment by knappa** [comment]
I actually started making a module that did as you say, but ran into trouble with an internal server error on girder. This was the "make it work now" solution while I figure out what was going on.

The "right" time interval for visualization will be tricky and will require input from the target audience. We don't want the 2d view to become cluttered & we want to provide detail so it ends up a question of balance.
